#!/bin/bash

# Script to update auth patterns in Supabase functions
# Generated by update-auth-patterns.js

echo "Updating auth patterns in 47 functions..."

echo "Updating admin-email-messages..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/admin-email-messages/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/admin-email-messages/index.ts

echo "admin-email-messages updated"
echo "Updating admin-operations..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/admin-operations/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/admin-operations/index.ts

echo "admin-operations updated"
echo "Updating calculate-sync-score..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/calculate-sync-score/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/calculate-sync-score/index.ts

echo "calculate-sync-score updated"
echo "Updating cancel-subscription..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/cancel-subscription/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/cancel-subscription/index.ts

echo "cancel-subscription updated"
echo "Updating chat-send..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/chat-send/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/chat-send/index.ts

echo "chat-send updated"
echo "Updating check-rate-limit..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/check-rate-limit/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/check-rate-limit/index.ts

echo "check-rate-limit updated"
echo "Updating contact-form-handler..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/contact-form-handler/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/contact-form-handler/index.ts

echo "contact-form-handler updated"
echo "Updating context-injector..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/context-injector/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/context-injector/index.ts

echo "context-injector updated"
echo "Updating create-payment-intent..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/create-payment-intent/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/create-payment-intent/index.ts

echo "create-payment-intent updated"
echo "Updating create-setup-intent..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/create-setup-intent/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/create-setup-intent/index.ts

echo "create-setup-intent updated"
echo "Updating credit-topup..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/credit-topup/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/credit-topup/index.ts

echo "credit-topup updated"
echo "Updating customer-portal..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/customer-portal/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/customer-portal/index.ts

echo "customer-portal updated"
echo "Updating email-verification..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/email-verification/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/email-verification/index.ts

echo "email-verification updated"
echo "Updating extract-user-memory..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/extract-user-memory/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/extract-user-memory/index.ts

echo "extract-user-memory updated"
echo "Updating folder-ai-handler..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/folder-ai-handler/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/folder-ai-handler/index.ts

echo "folder-ai-handler updated"
echo "Updating get-invoices..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/get-invoices/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/get-invoices/index.ts

echo "get-invoices updated"
echo "Updating get-payment-methods..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/get-payment-methods/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/get-payment-methods/index.ts

echo "get-payment-methods updated"
echo "Updating get-report-data..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/get-report-data/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/get-report-data/index.ts

echo "get-report-data updated"
echo "Updating github-list-repos..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/github-list-repos/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/github-list-repos/index.ts

echo "github-list-repos updated"
echo "Updating google-text-to-speech..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/google-text-to-speech/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/google-text-to-speech/index.ts

echo "google-text-to-speech updated"
echo "Updating google-whisper..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/google-whisper/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/google-whisper/index.ts

echo "google-whisper updated"
echo "Updating health-check..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/health-check/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/health-check/index.ts

echo "health-check updated"
echo "Updating image-generate..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/image-generate/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/image-generate/index.ts

echo "image-generate updated"
echo "Updating initiate-auth-report..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/initiate-auth-report/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/initiate-auth-report/index.ts

echo "initiate-auth-report updated"
echo "Updating keep-warm..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/keep-warm/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/keep-warm/index.ts

echo "keep-warm updated"
echo "Updating llm-handler-chatgpt..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/llm-handler-chatgpt/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/llm-handler-chatgpt/index.ts

echo "llm-handler-chatgpt updated"
echo "Updating llm-handler-gemini..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/llm-handler-gemini/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/llm-handler-gemini/index.ts

echo "llm-handler-gemini updated"
echo "Updating llm-handler-together-mode..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/llm-handler-together-mode/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/llm-handler-together-mode/index.ts

echo "llm-handler-together-mode updated"
echo "Updating llm-summarizer..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/llm-summarizer/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/llm-summarizer/index.ts

echo "llm-summarizer updated"
echo "Updating outbound-messenger..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/outbound-messenger/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/outbound-messenger/index.ts

echo "outbound-messenger updated"
echo "Updating password_token..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/password_token/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/password_token/index.ts

echo "password_token updated"
echo "Updating process-memory-buffer..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/process-memory-buffer/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/process-memory-buffer/index.ts

echo "process-memory-buffer updated"
echo "Updating report-orchestrator..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/report-orchestrator/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/report-orchestrator/index.ts

echo "report-orchestrator updated"
echo "Updating send-payment-notification..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/send-payment-notification/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/send-payment-notification/index.ts

echo "send-payment-notification updated"
echo "Updating set-default-payment-method..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/set-default-payment-method/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/set-default-payment-method/index.ts

echo "set-default-payment-method updated"
echo "Updating swiss..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/swiss/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/swiss/index.ts

echo "swiss updated"
echo "Updating translator-edge..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/translator-edge/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/translator-edge/index.ts

echo "translator-edge updated"
echo "Updating update-subscription..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/update-subscription/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/update-subscription/index.ts

echo "update-subscription updated"
echo "Updating validate-promo-code..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/validate-promo-code/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/validate-promo-code/index.ts

echo "validate-promo-code updated"
echo "Updating vbase-send-email..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/vbase-send-email/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/vbase-send-email/index.ts

echo "vbase-send-email updated"
echo "Updating verification-emailer..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/verification-emailer/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/verification-emailer/index.ts

echo "verification-emailer updated"
echo "Updating verify-checkout-session..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/verify-checkout-session/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/verify-checkout-session/index.ts

echo "verify-checkout-session updated"
echo "Updating conversation-manager..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/conversation-manager/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/conversation-manager/index.ts

echo "conversation-manager updated"
echo "Updating create-checkout..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/create-checkout/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/create-checkout/index.ts

echo "create-checkout updated"
echo "Updating create-subscription-checkout..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/create-subscription-checkout/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/create-subscription-checkout/index.ts

echo "create-subscription-checkout updated"
echo "Updating delete-account..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/delete-account/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/delete-account/index.ts

echo "delete-account updated"
echo "Updating generate-conversation-title..."
# Add imports
sed -i '1a import { withStandardHandling, withAuth, HttpError } from "../_shared/authHelper.ts";' supabase/functions/generate-conversation-title/index.ts

# Replace CORS headers (this is a simplified replacement - manual review needed)
# sed -i 's/const corsHeaders = {/const corsHeaders = getSecureCorsHeaders(req);/g' supabase/functions/generate-conversation-title/index.ts

echo "generate-conversation-title updated"

echo "Auth pattern updates complete!"
echo "Note: Manual review and testing required for each function"
