// This file is automatically generated. Do not edit it directly.
// 
// LOVABLE IDE REQUIREMENT: These credentials must be hardcoded for the IDE to work.
// The anon key (SUPABASE_PUBLISHABLE_KEY) is SAFE to expose - it's designed for frontend use
// and protected by Row Level Security (RLS). It cannot bypass RLS policies.
//
// SECURITY NOTE:
// - ✅ Anon key is safe to expose (protected by RLS)
// - ❌ NEVER hardcode the service_role_key here (it bypasses RLS)
// - ❌ NEVER commit .env files to git (use .env.example instead)

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrvqqvqvwqmfdqvqmaar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndydnFxdnF2d3FtZmRxdnFtYWFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1ODA0NjIsImV4cCI6MjA2MTE1NjQ2Mn0.u9P-SY4kSo7e16I29TXXSOJou5tErfYuldrr_CITWX0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Always provide an Authorization header for Edge Functions.
// - Default to the anon key when no user session exists (password reset, email verification, etc.)
// - Switch to the user's access token as soon as we have a session so RLS keeps working.
const setFunctionsAuth = (token?: string | null) => {
  const fallback = SUPABASE_PUBLISHABLE_KEY;
  supabase.functions.setAuth(token || fallback);
};

// Initialize with the currently cached session (if any)
supabase.auth.getSession().then(({ data }) => {
  setFunctionsAuth(data.session?.access_token);
}).catch(() => {
  setFunctionsAuth(undefined);
});

// React to auth state changes so Functions always carry the right JWT
supabase.auth.onAuthStateChange((_event, session) => {
  setFunctionsAuth(session?.access_token);
});